### ISSUE TITLE
Pin version of schematic in build workflow

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#128]
**Describe the bug**
Schematic is changing very rapidly, and it's hard to ensure that it functioning consistently for users on production (i.e. production is currently broken due to the workflow pulling in a newer version of schematic that is not compatible). We should pin to a specific version or commit to avoid automatically pulling in the latest version when building, and only update the pin when it has been tested on _develop_. This will also make rollbacks easier as the commit/version will be stored in git history.

**Comment by anngvu** [comment]
- [x] Determine best SHA to pin schematic for balance of least breakage and compatibility with model, DCA. This is somewhat difficult to figure out with schematic's lack of real versioning and a clear changelog, so spending too much time going through the issues and commit history. It seems that currently lists do not work at all. The NF model went back to list validation to accommodate a submission (https://github.com/nf-osi/nf-metadata-dictionary/pull/140), but that ended up with us between a rock and a hard place: Any single-value entries will fail validation because https://github.com/Sage-Bionetworks/schematic/issues/653 is still unresolved. But actual comma-delim list values also don't work, as documented both by you and Lingling: https://github.com/Sage-Bionetworks/schematic/issues/699 https://github.com/Sage-Bionetworks/schematic/issues/703. So manifests with lists can neither be newly submitted or updated.
- [x] Use alternative/more sensible workflow for https://github.com/nf-osi/NF_data_curator/blob/develop/.github/workflows/shinyapps_deploy.yml#L55

**Comment by allaway** [comment]
Could we consider this closed since we are now on the pypi releases?
