### ISSUE TITLE
change sidebar footer (Supported by ...) to match color scheme

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#13]
background and text color should match header

**Comment by allaway** [comment]
actually, this and #12 should probably also be defined in `www/config.json`, not in the body of the app like it currently is

**Comment by kthrog** [comment]
done!
currently live on staging

**Comment by allaway** [comment]
Looks good to me! I think the only change I'd make is to leave in the HTAN grant supported information - they should be acknowledged as the bulk of this software was supported by that grant

**Comment by allaway** [comment]
perhaps instead of the NF Data Portal logo we could have the NF OSI logo instead? what do you think?

**Comment by kthrog** [comment]
Good point on the acknowledging HTAN. Will add that back.

I could go either way on the logo. Do you have a sense of which is more recognizable? Since users need to upload their data on Synapse first, and they'll eventually submit their metadata back to Synapse, too, I don't know if bringing the portal into it is confusing?

**Comment by kthrog** [comment]
HTAN changes made and pushed.

**Comment by allaway** [comment]
I think that the NF-OSI logo is probably more appropriate - I agree that
bringing the portal in might be confusing (esp since the NF Data Portal is
a distinct piece of software). That's a different issue though, I'll file
that!
