### ISSUE TITLE
rallaway greeting from waiter when not logged into synapse?

### ISSUE THREAD

**Issue by kthrog** [nf-osi/NF_data_curator#20]
have noticed several times when I've launched the app without being first logged into Synapse that the loading screen (waiter) says 'welcome, rallaway' before disconnecting from the server.

**Comment by kthrog** [comment]
![image](https://user-images.githubusercontent.com/43977698/96471554-51f29480-11e4-11eb-8798-aa8ca80955fd.png)

**Comment by allaway** [comment]
Interesting...not sure what is going on there.

**Comment by allaway** [comment]
It wasn't clear to me whether this was being caused by my synapseConfig file on the server so I removed it.
Testing makes me think that this is resolved (ie. app goes straight to disconnect), but we should add error handling to let the user know what's happening (ie, they need to go and login and then reload).

**Comment by allaway** [comment]
Feel free to reopen if you see this again, though.

**Comment by kthrog** [comment]
Thanks! Looks fixed to me!
