### ISSUE TITLE
study/funder metadata

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#30]
What do you think about removing all of the study-level metadata from the various manifests that we have and creating a separate manifest for this information. I think that this would probably make the google sheets a bit snappier (`studyId` and `studyName` in particular are very big dropdowns), and it would allow the investigator to not worry too much about this information, which we can generally intuit simply from what project the data file is in (we could also write a script to apply these values programmatically on a project by project basis). 

In particular, I think we can put `studyName`, `studyId`, `initiative`, and `fundingAgency`. Any others? I'm hesitant to remove data-level metadata (eg `fileFormat`) because this could be really burdensome for us with and we could run into situations where we don't have the bandwidth to annotate all this expediently.

**Comment by kthrog** [comment]
I'm in favor of this in principle -- however, I have a few questions, and I'd love to know more about what's really required, when it comes to this kind of metadata, to enable discovery. Anywhere we can simplify and/or delegate to curation, to make the lives of data contributors easier, I'm almost definitely for it.

- If we don't collect `studyName` (or `id`), does this effect the data curator app's ability to upload the annotations to the right place? Or is this already configured when a user selects the project/folder they want to add metadata to, in step 1 on the app? 
- If no above, would we even need a manifest for these in the data curator app? I'm thinking not, since we'd be doing this on the back-end, as part of curation. 
- What about project-level annotations vs. file-level annotations? I'm really interested in utilizing project-level annotations more (they seem underutilized from my understanding, but they seem ready-made for this kind of use case) but this goes back to discovery use cases -- if we were to go this route, would it affect processes for discovery on the portal?
- If we need to stick with file-level annotations for discovery, then yes, I'm agreed I think it would be relatively minimal work to assign these all at once through a script. Maybe even, were we to collaborate a bit with IBC, we could automate this into a job that runs whenever a user uploads data (particularly for annotations that should remain constant in one project no matter what they are, eg `studyName`, `studyId`, `initiative`, and `fundingAgency`).

I agree we should continue to collect `fileFormat`from contributors, for the same reason you said. I think it's also what I'd consider a *signal* attribute, in that it's almost like a built-in warning to an annotator that they might not be uploading the right kind of data, if they can't find their file format in the drop down (or a warning to me that it's time to add a new data type).

**Comment by kthrog** [comment]
Also: this is basically the same issue as #23 , right?

**Comment by kthrog** [comment]
Removed (aka, shifted to their own schema for now) the following attributes:
```
- studyId
- studyName
- fundingAgency
- initiative
- projectNumber
- dhart
```
