### ISSUE TITLE
Add < rabbit > and determine how to handle species -- generic name or scientific name

### ISSUE THREAD

**Issue by kthrog** [nf-osi/NF_data_curator#46]
or species:Oryctolagus cuniculus

**Comment by kthrog** [comment]
Do some research on how other data portals, particularly outside Sage, handle this.

**Comment by allaway** [comment]
Due to a pressing need to get the Rabbit data annotated, I went ahead and added the scientific name to the schema csv (it's not yet in the json-ld, but will get incorporated in the next build). We can recode later if needed, but my preference is for the scientific name as there's a [robust taxonomy](https://www.ncbi.nlm.nih.gov/Taxonomy/), reducing (or even eliminating) semantic overlap, which is an annoying problem with some of our other annotations. :)

**Comment by kthrog** [comment]
I'm agreed on going forward with scientific names, both for precision's sake and for the taxonomy reason -- so that will be something I'll work on on the curation side. 

I also fixed the schema, since this broke Portal - Files on `species`, btw, something I noticed a little while ago when looking at something on the portal while doing the docs review for tomorrow. :)

**Comment by allaway** [comment]
Argh, good catch and my bad! You must have fixed it in the thirty minutes
or so between when I applied the annotations and checked up on them on the
portal because I didn't even notice!
